spring:
  application:
    name: hibertest
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/hibertest
    defaultUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 10000
      maxLifetime: 10000
      connection-timeout: 60000
  jpa:
    base-package: test.hiber.model
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        cache:
          use_second_level_cache: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      search:
        default:
          indexing_strategy: manual
          autoregister_listeners: false